# Generated by Django 4.2.1 on 2023-05-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_category_equipment_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Продукция/Товары', 'verbose_name_plural': 'Продукция/Товары'},
        ),
        migrations.AddField(
            model_name='equipment',
            name='time_create',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
